In [ ]:
#1. Why does this feature selection with chi2 fail?
from sklearn.feature_selection import SelectKBest, chi2

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [5]:
from sklearn.preprocessing import MinMaxScaler # input has negative values so used scaler
from sklearn.feature_selection import SelectKBest, chi2

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]
X_scaler= MinMaxScaler().fit_transform(X)
selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X_scaler, y)

In [ ]:
#2.
from sklearn.metrics.pairwise import cosine_similarity

# Error: strings instead of numerical features
user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']

similarity = cosine_similarity([user1], [user2])


In [9]:
from sklearn.metrics.pairwise import cosine_similarity

# Error: strings instead of numerical features
user1 = [1, 1, 0, 1]
user2 = [1, 0, 1, 1]

similarity = cosine_similarity([user1], [user2])
similarity

array([[0.66666667]])

In [ ]:
#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=5)  # more components than features
X_new = pca.fit_transform(X)


In [11]:
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=2)  # more components than features
X_new = pca.fit_transform(X)


In [ ]:
#4.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])

similarity = cosine_similarity(ratings)


In [14]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])
ratings_filled=np.nan_to_num(ratings)
similarity = cosine_similarity(ratings_filled)
similarity

array([[1.        , 0.68599434],
       [0.68599434, 1.        ]])

In [ ]:
#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

selector = RFE(estimator=LogisticRegression(), n_features_to_select=5)
selector.fit(X, y)  # Error: X and y not defined


In [16]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[2,3,4],[1,2,3],[5,6,7]]
y = [1,1,0]
selector = RFE(estimator=LogisticRegression(), n_features_to_select=5)
selector.fit(X, y)  # Error: X and y not defined


/Users/siva/anaconda3/lib/python3.13/site-packages/sklearn/feature_selection/_rfe.py:300: UserWarning: Found n_features_to_select=5 > n_features=3. There will be no feature selection and all features will be kept.
  warnings.warn(


,estimator,LogisticRegression()
,n_features_to_select,5
,step,1
,verbose,0
,importance_getter,'auto'
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1


In [ ]:
#6.from sklearn.metrics.pairwise import cosine_similarity

items = ["action movie", "romantic comedy", "sci-fi thriller"]
similarity = cosine_similarity([items[0]], [items[1]])


In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

items = ["action movie", "romantic comedy", "sci-fi thriller"]
#converted text uisng TfidVecorizer
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(items)

similarity = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])
similarity

array([[0.]])

In [ ]:
#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)


In [22]:
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1, 1]  # Error: mismatched dimensions
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)


In [ ]:
#8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5, 4, 3])
cosine_similarity(ratings, ratings)


In [24]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5, 4, 3]).reshape(1,-1)
cosine_similarity(ratings, ratings)


array([[1.]])

In [25]:
#9.
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)


ValueError: Input contains NaN.

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2], [3, 0], [4, 5]]
y = [0, 1, 0]

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)


,steps,"[('select', ...)]"
,transform_input,None
,memory,None
,verbose,False
,score_func,<function chi2 at 0x168797ce0>
,k,1


In [ ]:
#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [35]:
from sklearn.preprocessing import MaxAbsScaler
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, f_classif  # Changed from chi2 to f_classif as chi square can't handle negative values


X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

# MaxAbsScaler works with sparse matrices and handles negative values
X_scaled = MaxAbsScaler().fit_transform(X)

# Changed chi2 to f_classif which can handle negative values
selector = SelectKBest(score_func=f_classif, k=2)
X_new = selector.fit_transform(X, y)

/Users/siva/anaconda3/lib/python3.13/site-packages/sklearn/feature_selection/_univariate_selection.py:111: RuntimeWarning: divide by zero encountered in divide
  f = msb / msw
