In [ ]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)


In [3]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)
X_new

array([[2],
       [4],
       [6]])

In [ ]:
#2.
from sklearn.feature_selection import VarianceThreshold

X = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)


In [6]:
#2.
from sklearn.feature_selection import VarianceThreshold

X = [[0, 2, 1], [1, 1, 3], [2, 0, 2]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)
X_new

array([[0, 2, 1],
       [1, 1, 3],
       [2, 0, 2]])

In [ ]:
#3.
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [0, 0, 0]]
similarity = cosine_similarity(data)


In [8]:
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [1, 1, 1]] # cosine should not have zero value
similarity = cosine_similarity(data)
similarity

array([[1.        , 0.79211803],
       [0.79211803, 1.        ]])

In [ ]:
#4.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)


In [9]:
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)
X_new

array([[1],
       [3],
       [5]])

In [ ]:
#5.
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rate': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rating')


In [12]:
import pandas as pd
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rate': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rate')
pivot

item,I1,I2
user,,
A,5.0,3.0
B,NaN,4.0


In [ ]:
#6.
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=3)
X_new = pca.fit_transform(X)


In [14]:
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=2)# there were only two components
X_new = pca.fit_transform(X)
X_new

array([[-1.41421356e+00, -2.37213427e-17],
       [ 1.41421356e+00, -2.37213427e-17]])

In [ ]:
#7.
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
sim = cosine_similarity(ratings.T)


In [17]:
from sklearn.metrics.pairwise import cosine_similarity
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
sim = cosine_similarity(
    ratings.T.apply(lambda x: x.fillna(x.mean()), axis=1)# since none values are there, lambda fills it with mean of existing ratings
    
)
print(sim)

[[1.         0.9797959  0.91914503]
 [0.9797959  1.         0.96490128]
 [0.91914503 0.96490128 1.        ]]


In [ ]:
#8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


In [18]:
import numpy as np
# we need to maintain 2D vector for user_vec & item_vec
user_vec = np.array([[1, 2]])
item_vec = np.array([[0.5], [1.0]])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


Predicted Score: [[2.5]]


In [ ]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


In [20]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=3)# no of neighbors need to match array elements
print(indices)


[[0 2 1]]


In [ ]:
#10.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1])
b = np.array([0, 1, 1])

sim = cosine_similarity(a, b)
print("Similarity:", sim)

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
# it needs to 2D array for cosine similarity
a = np.array([[1, 0, 1]])
b = np.array([[0, 1, 1]])

sim = cosine_similarity(a, b)
print("Similarity:", sim)

Similarity: [[0.5]]
